# Generated by Django 4.1.7 on 2023-09-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='serial',
        ),
    ]
