# Generated by Django 4.1.7 on 2023-09-24 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_remove_robot_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='serial',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
