# Generated by Django 4.1.7 on 2023-09-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_robot_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
